### ISSUE TITLE
Codes are not syncing up

### ISSUE THREAD

**Issue by johnathanmartin** [PHPGangsta/GoogleAuthenticator#21]
I have been having a huge problem. I have not been able to figure out how to sync up the codes, when I use the $oneCode it gives me a number but its not the same as the one on my phone. Both are set to the correct time so I do not know what to do.

Please lend me any suggestions you have.

**Comment by PHPGangsta** [comment]
Hi Johnathan,
I don't know why they don't match, I would say only a wrong date+time or timezone can be the problem, they both have to match.
Can you check another Authenticator-App on your phone that is generating codes? Can you try it on another phone (that maybe has the correct time+timezone set)?

**Comment by Tigatok** [comment]
Hi PHPGangsta,

So if the server is in a different timezone, but I have clients all over the place, how can I make this work with anyone around the world? Are you saying that this will only work with people that are in the same timezone?

**Comment by PHPGangsta** [comment]
@Tigatok If you have the correct time via NTP on the webserver, you should not have a problem. I was talking about the client. I saw people who did not use NTP on the phone, but configured the time manually. They set the correct time, but an incorrect timezone. Then you get problems, because when getting the currect time im GMT/UTC, it's wrong.

Using NTP everywhere is the best advice, on client and server.
