### ISSUE TITLE
Reformate code to PSR-2

### ISSUE THREAD

**Issue by pgampe** [PHPGangsta/GoogleAuthenticator#39]
Reformat the code to follow PSR standards.

I suggest `friendsofphp/php-cs-fixer`.

**Comment by PHPGangsta** [comment]
A good idea! ;-)

Would you like to run it once, and create a PR with the fixes? Or so you suggest to run it within travis?

I also plan to move the class to src/ folder (instead of PHPGangsta), and use a namespace (GoogleAuthenticator). But that will break existing code of users. I guess I will tag the current version 1.0, and then create 2.0... Maybe you can help me a bit, it's my first public project where I have to think about things like that ;-)

**Comment by pgampe** [comment]
> Would you like to run it once, and create a PR with the fixes? Or do you suggest to run it within travis?

Running it with travis would be best, but running it once a while should be OK too, your project is not that big.

> I also plan to move the class to src/ folder (instead of PHPGangsta), and use a namespace 

Namespace would be good. Folder structure is up to tast, but should match the last part of the namespace (follow the PSR-4 standard).

> I guess I will tag the current version 1.0, and then create 2.0

Changing the basic API is very good reason to increase the major version.

> Maybe you can help me a bit, it's my first public project where I have to think about things like that ;-)

I can try ;)

My background is the [TYPO3 CMS project](https://github.com/TYPO3/TYPO3.CMS), which uses a rather sophisticated testing infrastructure.
