### ISSUE TITLE
Email verify

### ISSUE THREAD

**Issue by MrZsemle** [PHPGangsta/GoogleAuthenticator#73]
### Hi!
I would like to ask you how to create in the email verify code submissions. I would like to use the [PHPMailer](https://github.com/PHPMailer/PHPMailer) class for this. And the codes in the email would be valid for 5-10 minutes. How could this be done?

**Comment by RSpeekenbrink** [comment]
Generate a code via getCode() and verify the code with a discrepancy parameter passed to it. Discrepancy is the allowed time drift in 30 second units (8 means 4 minutes before or after). Since it's before or after the given timeslice you should save the timeslice somewhere and get that to validate against.

**Comment by MrZsemle** [comment]
Thank you!
